sp311_mvc_project/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using sp311_mvc_project.Data;
using sp311_mvc_project.Repositories.Products;
using sp311_mvc_project.Services;
using sp311_mvc_project.Settings;
using sp311_mvc_project.ViewModels;
using SQLitePCL;

namespace sp311_mvc_project.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _productRepository;

        public CartController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            var cartItems = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);
            cartItems ??= [];

            var products = _productRepository
                .GetAll()
                .Include(p => p.Category)
                .Where(p => cartItems.Select(i => i.ProductId).Contains(p.Id))
                .ToList();

            // Products quantity
            foreach (var product in products)
            {
                product.QuantityInCart = cartItems.First(i => i.ProductId == product.Id).Quantity;   
            }

            var cartVm = new CartVM
            {
                Products = products
            };

            return View(cartVm);
        }

        [HttpPost]
        public IActionResult AddToCart([FromBody] CartItemVM viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.ProductId))
                return BadRequest();

            var items = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);
            items ??= new List<CartItemVM>();

            if(items.Select(i => i.ProductId).Contains(viewModel.ProductId))
                return BadRequest();

            var newItems = items.ToList();
            newItems.Add(new CartItemVM { ProductId = viewModel.ProductId });
            HttpContext.Session.Set<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey, newItems);

            return Ok();
        }

        [HttpPost]
        public IActionResult RemoveFromCart([FromBody] CartItemVM viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.ProductId))
                return BadRequest();

            var items = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);

            if (items == null)
                return BadRequest();

            if (!items.Select(i => i.ProductId).Contains(viewModel.ProductId))
                return BadRequest();

            items = items.Where(i => i.ProductId != viewModel.ProductId);
            HttpContext.Session.Set(SessionSettings.SessionCartKey, items);

            return Ok();
        }

        public IActionResult IncreaseQuantity(string? id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            var cartItems = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);
            if (cartItems == null)
            {
                return RedirectToAction("Index");
            }

            var item = cartItems.FirstOrDefault(i => i.ProductId == id);
            var product = _productRepository.FindByIdAsync(id).Result;

            if(item != null && item.Quantity < product?.Amount)
            {
                item.Quantity++;
            }

            HttpContext.Session.Set(SessionSettings.SessionCartKey, cartItems);
            return RedirectToAction("Index");
        }

        public IActionResult DecreaseQuantity(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            var cartItems = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);
            if (cartItems == null)
            {
                return RedirectToAction("Index");
            }

            var item = cartItems.FirstOrDefault(i => i.ProductId == id);
            if (item != null && item.Quantity > 1)
            {
                item.Quantity--;
            }

            HttpContext.Session.Set(SessionSettings.SessionCartKey, cartItems);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Checkout()
        {
            var cartItems = HttpContext.Session.Get<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey);
            if(cartItems == null || cartItems.Count() == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var products = _productRepository
                .GetAll()
                .AsNoTracking()
                .Where(p => cartItems.Select(i => i.ProductId).Contains(p.Id))
                .ToList();

            foreach (var product in products)
            {
                product.Amount -= cartItems.First(i => i.ProductId == product.Id).Quantity;
            }

            await _productRepository.UpdateRangeAsync(products);
            HttpContext.Session.Set<IEnumerable<CartItemVM>>(SessionSettings.SessionCartKey, new List<CartItemVM>());

            return RedirectToAction("Index", "Home");
        }
    }
}

sp311_mvc_project/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using sp311_mvc_project.Data;
using sp311_mvc_project.Models;

namespace sp311_mvc_project.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var categories = _context.Categories.AsEnumerable();

            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category model)
        {
            model.Id = Guid.NewGuid().ToString();

            if(ModelState.IsValid)
            {
                _context.Categories.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult Edit(string? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var category = _context.Categories.FirstOrDefault(c => c.Id == id);

            if(category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category model)
        {
            _context.Categories.Update(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = _context.Categories.FirstOrDefault(c => c.Id == id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category model)
        {
            _context.Categories.Remove(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

sp311_mvc_project/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sp311_mvc_project.Data;
using sp311_mvc_project.Models;
using sp311_mvc_project.Repositories.Products;
using sp311_mvc_project.Services.Image;
using sp311_mvc_project.Settings;
using sp311_mvc_project.ViewModels;

namespace sp311_mvc_project.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IProductRepository _productRepository;
        private readonly IImageService _imageService;

        public ProductController(AppDbContext context, IProductRepository productRepository, IImageService imageService)
        {
            _context = context;
            _productRepository = productRepository;
            _imageService = imageService;
        }

        public IActionResult Index()
        {
            var products = _productRepository
                .GetAll()
                .Include(p => p.Category);

            return View(products);
        }

        public IActionResult Create()
        {
            var categories = _context.Categories.AsEnumerable();

            var viewModel = new CreateProductVM
            {
                Categories = new SelectList(categories, "Id", "Name")
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAsync(CreateProductVM viewModel)
        {
            string? fileName = null;

            if(viewModel.File != null)
            {
                fileName = await _imageService.SaveImageAsync(viewModel.File, PathSettings.ProductImagesPath);
            }

            viewModel.Product.Image = fileName;
            viewModel.Product.Id = Guid.NewGuid().ToString();

            await _productRepository.CreateAsync(viewModel.Product);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAsync(string? id)
        {
            if(id == null)
                return NotFound();

            var model = await _productRepository.FindByIdAsync(id);

            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(Product model)
        {
            if (model.Id == null)
                return NotFound();

            if(model.Image != null)
            {
                _imageService.DeleteImage(Path.Combine(PathSettings.ProductImagesPath, model.Image));
            }

            await _productRepository.DeleteAsync(model.Id);
            return RedirectToAction("Index");
        }
    }
}

sp311_mvc_project/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sp311_mvc_project</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sp311_mvc_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sp311_mvc_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Info">Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Товари</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категорії</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SetAdmin">Зробити адміном</a>
                        </li>
                        <li class="nav-item flex-grow-1 text-end">
                            <div class="d-flex justify-content-end">
                                <partial name="_LoginPartial" />
                                <div>
                                    <a asp-controller="Cart" asp-action="Index" style="color: black">
                                        <i class="bi bi-cart-fill header-basket__icon">
                                            <span class="header-basket__quan">
                                                @(HttpContextAccessor.HttpContext == null ? 0
                                                    : HttpContextAccessor.HttpContext.Session.GetCartItemsCount())
                                            </span>
                                        </i>
                                    </a>
                                </div>
                            </div>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - sp311_mvc_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
          selector: '#tinymceTextArea',
          license_key: 'gpl|1uqtscayd6yoj8amtn58u7jtdveb35cw36ksjkv62p74a8qt',
          plugins: 'image, link',
          toolbar: "image"
        });
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>